# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the eYs3D MIPI/CSI-RX drivers.
#
sp-vin-objs = sp-core.o sp-dma.o sp-v4l2.o

obj-$(CONFIG_VIDEO_EYS3D_eCV5546_CSI2)       += sp-csi2.o
obj-$(CONFIG_VIDEO_EYS3D_eCV5546_VIN)        += sp-vin.o
