# SPDX-License-I$(src)/dentifier: GPL-2.0
#
# Makefile for the eYs3D Geometric Distortion Correction driver.
#

obj-$(CONFIG_VIDEO_EYS3D_GDC)	+= gdc.o gdc-buf.o
obj-$(CONFIG_VIDEO_EYS3D_GDC_eCV5546)	+= gdc-ecv5546.o