dtb-$(CONFIG_eCV5546) += ecv5546-ev.dtb
dtb-$(CONFIG_eCV5546) += ecv5546-dm.dtb
dtb-$(CONFIG_eCV5546) += ecv5546-xink.dtb
dtb-$(CONFIG_eCV5546) += eCV5546-xink-v2.dtb
dtb-$(CONFIG_eCV5546) += ecv5546-xink-nano.dtb
