# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the eYs3D Pin control drivers.
#
obj-$(CONFIG_PINCTRL_eCV5546) += pinctrl-eys3d.o pinctrl-ecv5546.o gpio-ecv5546.o
obj-$(CONFIG_PINCTRL_SPPCTL) += sppinctrl.o
sppinctrl-objs := sppctl.o sppctl_sp7021.o
